name: Build OnePluss-Sm8250-Kernel
on:
  workflow_dispatch:
  schedule:
      # Run once a week on Sunday at midnight. See http://crontab.guru
      - cron: '0 21 * * *'
  push:
    branches:
      - HEAD
  pull_request:
      branches:
      - HEAD

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_MAXSIZE: "2G"
      CCACHE_HARDLINK: "true"
      KERNEL_DEFCONFIG: "kebab_ksu_defconfig"
      KERNEL_CMDLINE: "ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- LLVM=1 LLVM_IAS=1 O=out"
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 100

    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Install dependencies
      run: |
        sudo apt-get update -y 
        sudo apt install gcc-aarch64-linux-gnu -y
        sudo apt install gcc-arm-linux-gnueabi -y
        sudo apt install binutils make python3 libssl-dev build-essential bc  bison flex unzip libssl-dev ca-certificates xz-utils mkbootimg cpio device-tree-compiler git git-lfs wget -y
        sudo apt install binutils make python2 libssl-dev flex unzip libssl-dev ca-certificates xz-utils mkbootimg cpio device-tree-compiler git git-lfs bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev adb fastboot -y
        wget -O clang.tar.xz https://storage.xzr.moe/horizon-clang/Horizon-Clang-16.0.6.tar.xz
        mkdir clang
        cp clang.tar.xz clang/clang.tar.xz
        cd clang
        xz -dvf clang.tar.xz
        tar -xvf clang.tar
        cd ..
        bash syncanykernel3.sh
        rm -rf AnyKernel3/.git
        bash synckernelsu_all.sh
        bash init_modules.sh
    
    - name: GetTime
      id: get_time
      run: |
        echo "TIME=$(TZ=UTC-8 date +%m%d%H%M )" >> $GITHUB_OUTPUT

    - name: Build Kernel
      run: |
       export PATH=$(pwd)/clang/bin/:$PATH
       export ARCH=arm64
       export SUBARCH=arm64
       make $KERNEL_CMDLINE $KERNEL_DEFCONFIG CC="ccache clang"
       make $KERNEL_CMDLINE CC="ccache clang" -j$(nproc --all)
       cp out/arch/arm64/boot/Image.gz tools/AnyKernel3/Image.gz
       cp -vf tools/AnyKernel3_sh/anykernel.sh tools/AnyKernel3/
       cp -vf tools/AnyKernel3_sh/banner tools/AnyKernel3/

    - name: Upload Kernel
      uses: actions/upload-artifact@v3
      with:
        name: OnePlus8T-Horizon-KSU-${{ steps.get_time.outputs.TIME }}
        path: "tools/AnyKernel3/*"